apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.3.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: https://github.com/mmulholla/development/blob/main/charts/partners/test-org/psql-service/0.1.9/psql-service-0.1.9.tgz?raw=true
        digest: sha256:1b181bf2c5cdba414ed30970e00e89740f4a75ac7372fdc347fa5bd9cdf2e2fd
        digests:
            chart: sha256:1b181bf2c5cdba414ed30970e00e89740f4a75ac7372fdc347fa5bd9cdf2e2fd
        lastCertifiedTimestamp: "2021-11-01T17:12:37.148895-04:00"
        testedOpenShiftVersion: 4.8
        supportedOpenShiftVersions: 4.5 - 4.8
    chart:
        name: psql-service
        home: ""
        sources: []
        version: 0.1.11
        description: A Helm chart for a RedHat Certified PSQL
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 10.0.0
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: PSQL RedHat Demo Chart
            charts.openshift.io/provider: RedHat
            charts.openshift.io/supportURL: https://github.com/dperaza4dustbit/helm-chart
        kubeversion: 1.18 - 1.21
        dependencies: []
        type: application
    chart-overrides: ""
results:
  - check: v1.0/has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: v1.0/contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: v1.0/contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: v1.0/not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: v1.0/helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: v1.0/images-are-certified
    type: Mandatory
    outcome: PASS
    reason: 'Image is Red Hat certified : registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest'
  - check: v1.0/chart-testing
    type: Mandatory
    outcome: PASS
    reason: chart-testing passed.
  - check: v1.0/required-annotations-present
    type: Mandatory
    outcome: PASS
    reason: All required annotations present
  - check: v1.0/is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: v1.0/contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: v1.1/has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: v1.0/not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs

